#!/bin/bash
# Supabase Connection Troubleshooting - Get Correct Connection Details

echo "=============================================="
echo "Supabase Connection Troubleshooting"
echo "=============================================="
echo ""
echo "Issue: Network unreachable (IPv6 issue on UnoEuro)"
echo ""
echo "Your Supabase project: uuorwkqmuucqwdexevma"
echo "Project URL: https://uuorwkqmuucqwdexevma.supabase.co"
echo ""
echo "Solutions to try:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 1: Use IPv4 Pooler (Transaction Mode)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Go to Supabase Dashboard:"
echo "https://supabase.com/dashboard/project/uuorwkqmuucqwdexevma/settings/database"
echo ""
echo "Under 'Connection string', select 'Transaction' mode (IPv4 pooler)"
echo ""
echo "Update .env with:"
echo "DB_HOST=aws-0-eu-west-1.pooler.supabase.com"
echo "DB_PORT=5432"
echo "DB_DATABASE=postgres"
echo "DB_USERNAME=postgres.uuorwkqmuucqwdexevma"
echo "DB_PASSWORD=6NxmVNPdjoNs0fd9"
echo "DB_SSLMODE=require"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 2: IPv4 Direct Connection"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Force IPv4 by using alternative host format:"
echo "DB_HOST=aws-0-eu-west-1.aws.neon.tech"
echo ""
echo "Or check Supabase for IPv4-specific endpoint"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 3: Test Network Connectivity"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "On production server, test connectivity:"
echo ""
echo "# Test if IPv6 works"
echo "ping6 -c 3 db.uuorwkqmuucqwdexevma.supabase.co"
echo ""
echo "# Test IPv4 pooler"
echo "ping -c 3 aws-0-eu-west-1.pooler.supabase.com"
echo ""
echo "# Test port connectivity"
echo "nc -zv aws-0-eu-west-1.pooler.supabase.com 5432"
echo "nc -zv aws-0-eu-west-1.pooler.supabase.com 6543"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 4: Correct Connection String from Supabase"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/uuorwkqmuucqwdexevma"
echo "2. Click: Settings → Database"
echo "3. Look for: 'Connection string'"
echo "4. Select: 'URI' or 'Transaction' (not Session)"
echo "5. Copy the EXACT connection string shown"
echo "6. Parse it to get host, port, username, password"
echo ""
echo "Example formats:"
echo "postgresql://postgres.[ref]:[pass]@aws-0-[region].pooler.supabase.com:5432/postgres"
echo "postgresql://postgres.[ref]:[pass]@aws-0-[region].pooler.supabase.com:6543/postgres"
echo ""

